/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'site-pages': SitePage;
    'service-pages': ServicePage;
    'portfolio-projects': PortfolioProject;
    'portfolio-categories': PortfolioCategory;
    'journal-posts': JournalPost;
    'local-seo-pages': LocalSeoPage;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'site-pages': SitePagesSelect<false> | SitePagesSelect<true>;
    'service-pages': ServicePagesSelect<false> | ServicePagesSelect<true>;
    'portfolio-projects': PortfolioProjectsSelect<false> | PortfolioProjectsSelect<true>;
    'portfolio-categories': PortfolioCategoriesSelect<false> | PortfolioCategoriesSelect<true>;
    'journal-posts': JournalPostsSelect<false> | JournalPostsSelect<true>;
    'local-seo-pages': LocalSeoPagesSelect<false> | LocalSeoPagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    'site-settings': SiteSetting;
    'global-ctas': GlobalCta;
    footer: Footer;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'global-ctas': GlobalCtasSelect<false> | GlobalCtasSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Standardseiten wie Startseite, About, Kontakt, Uebersichten und Legal-Seiten.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-pages".
 */
export interface SitePage {
  id: number;
  title: string;
  /**
   * Wird aus dem Titel erzeugt, kann aber bewusst angepasst werden.
   */
  slug: string;
  pageType:
    | 'home'
    | 'about'
    | 'contact'
    | 'photography-index'
    | 'portfolio-index'
    | 'services-index'
    | 'journal-index'
    | 'legal';
  intro?: string | null;
  /**
   * Bild aus dem Medienarchiv waehlen. Neue Bilder koennen direkt im Drawer hochgeladen und bearbeitet werden.
   */
  heroImage?: (number | null) | Media;
  /**
   * Optional. Wenn leer, nutzt das System automatisch das Hero-Bild.
   */
  teaserImage?: (number | null) | Media;
  /**
   * Optionale Inhaltsmodule. Fuer reine Bildwechsel sind die Bildfelder der jeweiligen Seite schneller.
   */
  blocks?:
    | (
        | {
            eyebrow?: string | null;
            headline?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            headline?: string | null;
            layout?: ('editorial-strip' | 'contact-sheet' | 'stage' | 'single-large') | null;
            items?:
              | {
                  /**
                   * Bild fuer diese Position in der Sequenz.
                   */
                  image: number | Media;
                  caption?: string | null;
                  cropIntent?: ('auto' | 'protect-detail' | 'protect-space' | 'dramatic-crop') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageSequence';
          }
        | {
            quote: string;
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteBlock';
          }
        | {
            headline?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
        | {
            headline?: string | null;
            links?:
              | {
                  label: string;
                  /**
                   * Interne Links am besten root-relativ eintragen, z. B. /portfolio. Vollstaendige eigene URLs werden automatisch gekuerzt.
                   */
                  href: string;
                  description?: string | null;
                  seoPurpose?: ('contextual' | 'navigation' | 'conversion' | 'citation' | 'legal' | 'social') | null;
                  rel?: ('follow' | 'nofollow' | 'sponsored' | 'ugc') | null;
                  openInNewTab?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'linkList';
          }
        | {
            headline: string;
            text?: string | null;
            buttonLabel?: string | null;
            emailSubject?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBlock';
          }
      )[]
    | null;
  contactOverride?: {
    headline?: string | null;
    text?: string | null;
    emailSubject?: string | null;
  };
  /**
   * Wird beim Speichern automatisch aus Titel, Intro/Kurztext und Bildfeldern vorbereitet. Nur fuer bewusste Overrides oeffnen.
   */
  seo?: {
    /**
     * Optionaler Override. Wenn leer, wird der Titel automatisch aus dem Seitentitel erzeugt.
     */
    title?: string | null;
    /**
     * Optionaler Override. Wenn leer, wird eine knappe Beschreibung aus Kurztext oder Intro erzeugt.
     */
    description?: string | null;
    /**
     * Optionaler redaktioneller Fokus fuer Snippet, interne Links und spaetere LLM-Vorschlaege.
     */
    focusKeyword?: string | null;
    /**
     * Optional: verwandte Suchbegriffe oder Clusterbegriffe. Nicht stumpf im Text wiederholen.
     */
    secondaryKeywords?: string[] | null;
    /**
     * Hilft beim Schreiben von Title, Description, H1 und internen Links.
     */
    searchIntent?: ('informational' | 'commercial' | 'local' | 'transactional' | 'navigational') | null;
    /**
     * Gewuenschte Anchor-Texte fuer interne Links zu dieser Seite.
     */
    internalLinkAnchors?: string[] | null;
    /**
     * Optionaler Override. Legacy-URLs oder neue Routen werden automatisch vorgeschlagen.
     */
    canonicalUrl?: string | null;
    /**
     * Interne Migrationsnotiz, z. B. portfolio.html oder /automobil-fotografie-duesseldorf.html.
     */
    legacyUrl?: string | null;
    /**
     * Fallback ist das Hero- oder Coverbild. Fuer Social Preview idealerweise 1200x630-nah.
     */
    ogImage?: (number | null) | Media;
    /**
     * Nur für Entwürfe, Übergangsseiten oder bewusst private Inhalte aktivieren.
     */
    noIndex?: boolean | null;
  };
  /**
   * Technische Herkunft aus der alten HTML-Website. Hilft beim URL-Erhalt, Review und schrittweisen 1:1-Nachbau.
   */
  legacy?: {
    sourceFile?: string | null;
    sourceUrl?: string | null;
    migrationStatus?: ('seeded' | 'reviewed' | 'componentized' | 'live') | null;
    /**
     * Technischer Status fuer Astro: legacy-file und payload-legacy-html sind reine Migrations-/Archivzustaende. native-component und structured-blocks sind release-faehige Ausgabeformen ohne rohes Body-HTML.
     */
    renderSource?: ('legacy-file' | 'payload-legacy-html' | 'native-component' | 'structured-blocks') | null;
    /**
     * Aus der alten Seite extrahierter Head fuer die 1:1-Vorschau und Parity-Routen.
     */
    renderedHeadHtml?: string | null;
    /**
     * Header und Footer sind entfernt. Astro rendert diesen Body aus Payload, solange der Seitentyp noch nicht komplett in strukturierte Komponenten zerlegt ist.
     */
    renderedBodyHtml?: string | null;
    /**
     * Legacy-Skripte und Lightbox-Markup, die nach dem Footer standen.
     */
    afterFooterHtml?: string | null;
    bodyClass?: string | null;
    headerCurrent?: string | null;
    extractedHeadings?: string[] | null;
    extractedImagePaths?: string[] | null;
    /**
     * Reiner Text aus der alten Seite als redaktionelle Kontrollbasis.
     */
    extractedText?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Zentrale Bildbibliothek mit Vorschau, Alt-Texten, Bildstimmung, Verwendungszweck, Focal Point und responsiven Derivaten.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Redaktioneller Name, nicht nur Dateiname.
   */
  title: string;
  /**
   * Pflichtfeld: beschreibt das Bild knapp fuer SEO und Barrierefreiheit.
   */
  alt: string;
  /**
   * Optionaler sichtbarer Begleittext fuer Galerien, Journal oder Portfolio.
   */
  caption?: string | null;
  /**
   * Fuer besonders starke Motive, die als Hero oder Portfolio-Teaser in Frage kommen.
   */
  featured?: boolean | null;
  category?:
    | ('uncategorized' | 'portrait' | 'automotive' | 'oldtimer' | 'motorrad' | 'landschaft' | 'service' | 'atmosphere')
    | null;
  /**
   * Freie Schlagworte, z. B. Duesseldorf, Nacht, Showroom, Detail, Kampagne.
   */
  tags?: string[] | null;
  /**
   * Wird beim Upload automatisch vorbelegt und kann manuell korrigiert werden.
   */
  orientation?: ('portrait' | 'landscape' | 'square' | 'panorama') | null;
  /**
   * Hilft spaeter beim Filtern und Wiederfinden geeigneter Bilder.
   */
  imageType?:
    | (
        | 'portrait'
        | 'automotive'
        | 'landscape'
        | 'motorcycle'
        | 'detail'
        | 'editorial'
        | 'atmosphere'
        | 'behind-the-scenes'
      )[]
    | null;
  visualTone?:
    | ('dark-cinematic' | 'light-editorial' | 'warm-atmospheric' | 'cool-technical' | 'detail-texture')[]
    | null;
  usagePurpose?: ('hero' | 'teaser' | 'gallery' | 'social' | 'local-seo' | 'print' | 'internal-only')[] | null;
  /**
   * Zum Beispiel: gutes Hero-Motiv, nicht stark beschneiden, fuer Portfolio-Teaser geeignet.
   */
  usageNotes?: string | null;
  /**
   * Automatisch fuer Platzhalter-Hintergruende erzeugt.
   */
  dominantColor?: string | null;
  /**
   * Automatisch erzeugte Mini-WebP-Version als Data URL.
   */
  blurDataUrl?: string | null;
  /**
   * Pfad aus der alten HTML-/Assets-Struktur, damit Bildverwendung nachvollziehbar bleibt.
   */
  legacySourcePath?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    mobile?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    mobileAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    cardAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    heroAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wideAvif?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Leistungsseite mit alter URL, Hero, Nutzenargumenten, FAQ, CTA und SEO.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-pages".
 */
export interface ServicePage {
  id: number;
  title: string;
  /**
   * Wird aus dem Titel erzeugt, kann aber bewusst angepasst werden.
   */
  slug: string;
  featured?: boolean | null;
  sortOrder?: number | null;
  /**
   * Wird beim Speichern aus Titel oder Slug vorgeschlagen, falls leer.
   */
  serviceType:
    | 'automotive'
    | 'sportwagen'
    | 'oldtimer'
    | 'motorrad'
    | 'portrait'
    | 'landschaft'
    | 'fotolabor'
    | 'grossformatdruck'
    | 'werbetechnik'
    | 'webdesign-seo'
    | 'videografie'
    | 'other';
  intro: string;
  /**
   * Grosses Leitmotiv der Seite. Wird auch als Social-Bild genutzt, wenn kein OG-Bild gesetzt ist.
   */
  heroImage: number | Media;
  /**
   * Optional. Wenn leer, nutzt das System automatisch das Hero-Bild.
   */
  teaserImage?: (number | null) | Media;
  audience?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  proofPoints?:
    | {
        label: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optionale Inhaltsmodule. Fuer reine Bildwechsel sind die Bildfelder der jeweiligen Seite schneller.
   */
  blocks?:
    | (
        | {
            eyebrow?: string | null;
            headline?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            headline?: string | null;
            layout?: ('editorial-strip' | 'contact-sheet' | 'stage' | 'single-large') | null;
            items?:
              | {
                  /**
                   * Bild fuer diese Position in der Sequenz.
                   */
                  image: number | Media;
                  caption?: string | null;
                  cropIntent?: ('auto' | 'protect-detail' | 'protect-space' | 'dramatic-crop') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageSequence';
          }
        | {
            quote: string;
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteBlock';
          }
        | {
            headline?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
        | {
            headline?: string | null;
            links?:
              | {
                  label: string;
                  /**
                   * Interne Links am besten root-relativ eintragen, z. B. /portfolio. Vollstaendige eigene URLs werden automatisch gekuerzt.
                   */
                  href: string;
                  description?: string | null;
                  seoPurpose?: ('contextual' | 'navigation' | 'conversion' | 'citation' | 'legal' | 'social') | null;
                  rel?: ('follow' | 'nofollow' | 'sponsored' | 'ugc') | null;
                  openInNewTab?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'linkList';
          }
        | {
            headline: string;
            text?: string | null;
            buttonLabel?: string | null;
            emailSubject?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBlock';
          }
      )[]
    | null;
  relatedPages?:
    | {
        label: string;
        /**
         * Interne Links am besten root-relativ eintragen, z. B. /portfolio. Vollstaendige eigene URLs werden automatisch gekuerzt.
         */
        href: string;
        seoPurpose?: ('contextual' | 'navigation' | 'conversion' | 'citation' | 'legal' | 'social') | null;
        rel?: ('follow' | 'nofollow' | 'sponsored' | 'ugc') | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    headline?: string | null;
    text?: string | null;
    buttonLabel?: string | null;
    emailSubject?: string | null;
  };
  /**
   * Wird beim Speichern automatisch aus Titel, Intro/Kurztext und Bildfeldern vorbereitet. Nur fuer bewusste Overrides oeffnen.
   */
  seo?: {
    /**
     * Optionaler Override. Wenn leer, wird der Titel automatisch aus dem Seitentitel erzeugt.
     */
    title?: string | null;
    /**
     * Optionaler Override. Wenn leer, wird eine knappe Beschreibung aus Kurztext oder Intro erzeugt.
     */
    description?: string | null;
    /**
     * Optionaler redaktioneller Fokus fuer Snippet, interne Links und spaetere LLM-Vorschlaege.
     */
    focusKeyword?: string | null;
    /**
     * Optional: verwandte Suchbegriffe oder Clusterbegriffe. Nicht stumpf im Text wiederholen.
     */
    secondaryKeywords?: string[] | null;
    /**
     * Hilft beim Schreiben von Title, Description, H1 und internen Links.
     */
    searchIntent?: ('informational' | 'commercial' | 'local' | 'transactional' | 'navigational') | null;
    /**
     * Gewuenschte Anchor-Texte fuer interne Links zu dieser Seite.
     */
    internalLinkAnchors?: string[] | null;
    /**
     * Optionaler Override. Legacy-URLs oder neue Routen werden automatisch vorgeschlagen.
     */
    canonicalUrl?: string | null;
    /**
     * Interne Migrationsnotiz, z. B. portfolio.html oder /automobil-fotografie-duesseldorf.html.
     */
    legacyUrl?: string | null;
    /**
     * Fallback ist das Hero- oder Coverbild. Fuer Social Preview idealerweise 1200x630-nah.
     */
    ogImage?: (number | null) | Media;
    /**
     * Nur für Entwürfe, Übergangsseiten oder bewusst private Inhalte aktivieren.
     */
    noIndex?: boolean | null;
  };
  /**
   * Technische Herkunft aus der alten HTML-Website. Hilft beim URL-Erhalt, Review und schrittweisen 1:1-Nachbau.
   */
  legacy?: {
    sourceFile?: string | null;
    sourceUrl?: string | null;
    migrationStatus?: ('seeded' | 'reviewed' | 'componentized' | 'live') | null;
    /**
     * Technischer Status fuer Astro: legacy-file und payload-legacy-html sind reine Migrations-/Archivzustaende. native-component und structured-blocks sind release-faehige Ausgabeformen ohne rohes Body-HTML.
     */
    renderSource?: ('legacy-file' | 'payload-legacy-html' | 'native-component' | 'structured-blocks') | null;
    /**
     * Aus der alten Seite extrahierter Head fuer die 1:1-Vorschau und Parity-Routen.
     */
    renderedHeadHtml?: string | null;
    /**
     * Header und Footer sind entfernt. Astro rendert diesen Body aus Payload, solange der Seitentyp noch nicht komplett in strukturierte Komponenten zerlegt ist.
     */
    renderedBodyHtml?: string | null;
    /**
     * Legacy-Skripte und Lightbox-Markup, die nach dem Footer standen.
     */
    afterFooterHtml?: string | null;
    bodyClass?: string | null;
    headerCurrent?: string | null;
    extractedHeadings?: string[] | null;
    extractedImagePaths?: string[] | null;
    /**
     * Reiner Text aus der alten Seite als redaktionelle Kontrollbasis.
     */
    extractedText?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Kuratiertes Projekt mit Cover, Galerie, Kontext, SEO und Vorschau.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-projects".
 */
export interface PortfolioProject {
  id: number;
  title: string;
  /**
   * Wird aus dem Titel erzeugt, kann aber bewusst angepasst werden.
   */
  slug: string;
  featured?: boolean | null;
  /**
   * Kleinere Werte erscheinen weiter oben.
   */
  sortOrder?: number | null;
  publishedAt?: string | null;
  category: number | PortfolioCategory;
  excerpt: string;
  /**
   * Kurz notieren, wofuer die Serie gedacht ist: Verkauf, Kampagne, Print, Website, freie Arbeit.
   */
  usageSummary?: string | null;
  year?: string | null;
  location?: string | null;
  client?: string | null;
  /**
   * Leitmotiv fuer Projektseite, Portfolio-Karte und Social Preview.
   */
  coverImage: number | Media;
  /**
   * Die Reihenfolge ist die sichtbare Reihenfolge im Portfolio. Fuer einen schnellen Austausch reicht meistens: Bild oeffnen, anderes Medium waehlen, speichern.
   */
  gallery?:
    | {
        /**
         * Dieses Motiv wird an dieser Position in der Bildstrecke angezeigt.
         */
        image: number | Media;
        caption?: string | null;
        /**
         * Nur fuer die Bildregie. Die wichtigsten Rollen sind Hero, Sequenz, Detail und Abschluss.
         */
        role?: ('hero' | 'sequence' | 'detail' | 'closing') | null;
        id?: string | null;
      }[]
    | null;
  relatedServices?: (number | ServicePage)[] | null;
  /**
   * Optionale Inhaltsmodule. Fuer reine Bildwechsel sind die Bildfelder der jeweiligen Seite schneller.
   */
  blocks?:
    | (
        | {
            eyebrow?: string | null;
            headline?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            headline?: string | null;
            layout?: ('editorial-strip' | 'contact-sheet' | 'stage' | 'single-large') | null;
            items?:
              | {
                  /**
                   * Bild fuer diese Position in der Sequenz.
                   */
                  image: number | Media;
                  caption?: string | null;
                  cropIntent?: ('auto' | 'protect-detail' | 'protect-space' | 'dramatic-crop') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageSequence';
          }
        | {
            quote: string;
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteBlock';
          }
        | {
            headline?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
        | {
            headline?: string | null;
            links?:
              | {
                  label: string;
                  /**
                   * Interne Links am besten root-relativ eintragen, z. B. /portfolio. Vollstaendige eigene URLs werden automatisch gekuerzt.
                   */
                  href: string;
                  description?: string | null;
                  seoPurpose?: ('contextual' | 'navigation' | 'conversion' | 'citation' | 'legal' | 'social') | null;
                  rel?: ('follow' | 'nofollow' | 'sponsored' | 'ugc') | null;
                  openInNewTab?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'linkList';
          }
        | {
            headline: string;
            text?: string | null;
            buttonLabel?: string | null;
            emailSubject?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBlock';
          }
      )[]
    | null;
  /**
   * Der Default funktioniert fuer die meisten Serien.
   */
  presentationMode?: ('floating-archive' | 'narrative-stage' | 'experimental-lens' | 'editorial') | null;
  cta?: {
    headline?: string | null;
    text?: string | null;
    buttonLabel?: string | null;
    emailSubject?: string | null;
  };
  /**
   * Wird beim Speichern automatisch aus Titel, Intro/Kurztext und Bildfeldern vorbereitet. Nur fuer bewusste Overrides oeffnen.
   */
  seo?: {
    /**
     * Optionaler Override. Wenn leer, wird der Titel automatisch aus dem Seitentitel erzeugt.
     */
    title?: string | null;
    /**
     * Optionaler Override. Wenn leer, wird eine knappe Beschreibung aus Kurztext oder Intro erzeugt.
     */
    description?: string | null;
    /**
     * Optionaler redaktioneller Fokus fuer Snippet, interne Links und spaetere LLM-Vorschlaege.
     */
    focusKeyword?: string | null;
    /**
     * Optional: verwandte Suchbegriffe oder Clusterbegriffe. Nicht stumpf im Text wiederholen.
     */
    secondaryKeywords?: string[] | null;
    /**
     * Hilft beim Schreiben von Title, Description, H1 und internen Links.
     */
    searchIntent?: ('informational' | 'commercial' | 'local' | 'transactional' | 'navigational') | null;
    /**
     * Gewuenschte Anchor-Texte fuer interne Links zu dieser Seite.
     */
    internalLinkAnchors?: string[] | null;
    /**
     * Optionaler Override. Legacy-URLs oder neue Routen werden automatisch vorgeschlagen.
     */
    canonicalUrl?: string | null;
    /**
     * Interne Migrationsnotiz, z. B. portfolio.html oder /automobil-fotografie-duesseldorf.html.
     */
    legacyUrl?: string | null;
    /**
     * Fallback ist das Hero- oder Coverbild. Fuer Social Preview idealerweise 1200x630-nah.
     */
    ogImage?: (number | null) | Media;
    /**
     * Nur für Entwürfe, Übergangsseiten oder bewusst private Inhalte aktivieren.
     */
    noIndex?: boolean | null;
  };
  /**
   * Technische Herkunft aus der alten HTML-Website. Hilft beim URL-Erhalt, Review und schrittweisen 1:1-Nachbau.
   */
  legacy?: {
    sourceFile?: string | null;
    sourceUrl?: string | null;
    migrationStatus?: ('seeded' | 'reviewed' | 'componentized' | 'live') | null;
    /**
     * Technischer Status fuer Astro: legacy-file und payload-legacy-html sind reine Migrations-/Archivzustaende. native-component und structured-blocks sind release-faehige Ausgabeformen ohne rohes Body-HTML.
     */
    renderSource?: ('legacy-file' | 'payload-legacy-html' | 'native-component' | 'structured-blocks') | null;
    /**
     * Aus der alten Seite extrahierter Head fuer die 1:1-Vorschau und Parity-Routen.
     */
    renderedHeadHtml?: string | null;
    /**
     * Header und Footer sind entfernt. Astro rendert diesen Body aus Payload, solange der Seitentyp noch nicht komplett in strukturierte Komponenten zerlegt ist.
     */
    renderedBodyHtml?: string | null;
    /**
     * Legacy-Skripte und Lightbox-Markup, die nach dem Footer standen.
     */
    afterFooterHtml?: string | null;
    bodyClass?: string | null;
    headerCurrent?: string | null;
    extractedHeadings?: string[] | null;
    extractedImagePaths?: string[] | null;
    /**
     * Reiner Text aus der alten Seite als redaktionelle Kontrollbasis.
     */
    extractedText?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Portfolio-Kategorien fuer Filter, Uebersichten und spaetere Migrationssteuerung.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-categories".
 */
export interface PortfolioCategory {
  id: number;
  title: string;
  /**
   * Wird aus dem Titel erzeugt, kann aber bewusst angepasst werden.
   */
  slug: string;
  sortOrder?: number | null;
  intro?: string | null;
  /**
   * Bild aus dem Medienarchiv waehlen. Neue Bilder koennen direkt im Drawer hochgeladen und bearbeitet werden.
   */
  coverImage?: (number | null) | Media;
  /**
   * Wird beim Speichern automatisch aus Titel, Intro/Kurztext und Bildfeldern vorbereitet. Nur fuer bewusste Overrides oeffnen.
   */
  seo?: {
    /**
     * Optionaler Override. Wenn leer, wird der Titel automatisch aus dem Seitentitel erzeugt.
     */
    title?: string | null;
    /**
     * Optionaler Override. Wenn leer, wird eine knappe Beschreibung aus Kurztext oder Intro erzeugt.
     */
    description?: string | null;
    /**
     * Optionaler redaktioneller Fokus fuer Snippet, interne Links und spaetere LLM-Vorschlaege.
     */
    focusKeyword?: string | null;
    /**
     * Optional: verwandte Suchbegriffe oder Clusterbegriffe. Nicht stumpf im Text wiederholen.
     */
    secondaryKeywords?: string[] | null;
    /**
     * Hilft beim Schreiben von Title, Description, H1 und internen Links.
     */
    searchIntent?: ('informational' | 'commercial' | 'local' | 'transactional' | 'navigational') | null;
    /**
     * Gewuenschte Anchor-Texte fuer interne Links zu dieser Seite.
     */
    internalLinkAnchors?: string[] | null;
    /**
     * Optionaler Override. Legacy-URLs oder neue Routen werden automatisch vorgeschlagen.
     */
    canonicalUrl?: string | null;
    /**
     * Interne Migrationsnotiz, z. B. portfolio.html oder /automobil-fotografie-duesseldorf.html.
     */
    legacyUrl?: string | null;
    /**
     * Fallback ist das Hero- oder Coverbild. Fuer Social Preview idealerweise 1200x630-nah.
     */
    ogImage?: (number | null) | Media;
    /**
     * Nur für Entwürfe, Übergangsseiten oder bewusst private Inhalte aktivieren.
     */
    noIndex?: boolean | null;
  };
  /**
   * Technische Herkunft aus der alten HTML-Website. Hilft beim URL-Erhalt, Review und schrittweisen 1:1-Nachbau.
   */
  legacy?: {
    sourceFile?: string | null;
    sourceUrl?: string | null;
    migrationStatus?: ('seeded' | 'reviewed' | 'componentized' | 'live') | null;
    /**
     * Technischer Status fuer Astro: legacy-file und payload-legacy-html sind reine Migrations-/Archivzustaende. native-component und structured-blocks sind release-faehige Ausgabeformen ohne rohes Body-HTML.
     */
    renderSource?: ('legacy-file' | 'payload-legacy-html' | 'native-component' | 'structured-blocks') | null;
    /**
     * Aus der alten Seite extrahierter Head fuer die 1:1-Vorschau und Parity-Routen.
     */
    renderedHeadHtml?: string | null;
    /**
     * Header und Footer sind entfernt. Astro rendert diesen Body aus Payload, solange der Seitentyp noch nicht komplett in strukturierte Komponenten zerlegt ist.
     */
    renderedBodyHtml?: string | null;
    /**
     * Legacy-Skripte und Lightbox-Markup, die nach dem Footer standen.
     */
    afterFooterHtml?: string | null;
    bodyClass?: string | null;
    headerCurrent?: string | null;
    extractedHeadings?: string[] | null;
    extractedImagePaths?: string[] | null;
    /**
     * Reiner Text aus der alten Seite als redaktionelle Kontrollbasis.
     */
    extractedText?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Journal-Beitrag mit Cover, Excerpt, Artikel-SEO, internen Links und Vorschau.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-posts".
 */
export interface JournalPost {
  id: number;
  title: string;
  /**
   * Wird aus dem Titel erzeugt, kann aber bewusst angepasst werden.
   */
  slug: string;
  featured?: boolean | null;
  category: 'behind-the-scenes' | 'automotive' | 'portrait' | 'landscape-print' | 'process';
  publishedAt: string;
  excerpt: string;
  /**
   * Wird als Artikelbild und als Social-Bild genutzt, wenn kein OG-Bild gesetzt ist.
   */
  coverImage: number | Media;
  tags?: string[] | null;
  relatedPages?:
    | {
        label: string;
        /**
         * Interne Links am besten root-relativ eintragen, z. B. /portfolio. Vollstaendige eigene URLs werden automatisch gekuerzt.
         */
        href: string;
        seoPurpose?: ('contextual' | 'navigation' | 'conversion' | 'citation' | 'legal' | 'social') | null;
        rel?: ('follow' | 'nofollow' | 'sponsored' | 'ugc') | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optionale Inhaltsmodule. Fuer reine Bildwechsel sind die Bildfelder der jeweiligen Seite schneller.
   */
  blocks?:
    | (
        | {
            eyebrow?: string | null;
            headline?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            headline?: string | null;
            layout?: ('editorial-strip' | 'contact-sheet' | 'stage' | 'single-large') | null;
            items?:
              | {
                  /**
                   * Bild fuer diese Position in der Sequenz.
                   */
                  image: number | Media;
                  caption?: string | null;
                  cropIntent?: ('auto' | 'protect-detail' | 'protect-space' | 'dramatic-crop') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageSequence';
          }
        | {
            quote: string;
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteBlock';
          }
        | {
            headline?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
        | {
            headline?: string | null;
            links?:
              | {
                  label: string;
                  /**
                   * Interne Links am besten root-relativ eintragen, z. B. /portfolio. Vollstaendige eigene URLs werden automatisch gekuerzt.
                   */
                  href: string;
                  description?: string | null;
                  seoPurpose?: ('contextual' | 'navigation' | 'conversion' | 'citation' | 'legal' | 'social') | null;
                  rel?: ('follow' | 'nofollow' | 'sponsored' | 'ugc') | null;
                  openInNewTab?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'linkList';
          }
        | {
            headline: string;
            text?: string | null;
            buttonLabel?: string | null;
            emailSubject?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBlock';
          }
      )[]
    | null;
  /**
   * Wird aus Inhalt und Excerpt geschaetzt, wenn leer.
   */
  readingTime?: number | null;
  /**
   * Wird beim Speichern automatisch aus Titel, Intro/Kurztext und Bildfeldern vorbereitet. Nur fuer bewusste Overrides oeffnen.
   */
  seo?: {
    /**
     * Optionaler Override. Wenn leer, wird der Titel automatisch aus dem Seitentitel erzeugt.
     */
    title?: string | null;
    /**
     * Optionaler Override. Wenn leer, wird eine knappe Beschreibung aus Kurztext oder Intro erzeugt.
     */
    description?: string | null;
    /**
     * Optionaler redaktioneller Fokus fuer Snippet, interne Links und spaetere LLM-Vorschlaege.
     */
    focusKeyword?: string | null;
    /**
     * Optional: verwandte Suchbegriffe oder Clusterbegriffe. Nicht stumpf im Text wiederholen.
     */
    secondaryKeywords?: string[] | null;
    /**
     * Hilft beim Schreiben von Title, Description, H1 und internen Links.
     */
    searchIntent?: ('informational' | 'commercial' | 'local' | 'transactional' | 'navigational') | null;
    /**
     * Gewuenschte Anchor-Texte fuer interne Links zu dieser Seite.
     */
    internalLinkAnchors?: string[] | null;
    /**
     * Optionaler Override. Legacy-URLs oder neue Routen werden automatisch vorgeschlagen.
     */
    canonicalUrl?: string | null;
    /**
     * Interne Migrationsnotiz, z. B. portfolio.html oder /automobil-fotografie-duesseldorf.html.
     */
    legacyUrl?: string | null;
    /**
     * Fallback ist das Hero- oder Coverbild. Fuer Social Preview idealerweise 1200x630-nah.
     */
    ogImage?: (number | null) | Media;
    /**
     * Nur für Entwürfe, Übergangsseiten oder bewusst private Inhalte aktivieren.
     */
    noIndex?: boolean | null;
  };
  /**
   * Technische Herkunft aus der alten HTML-Website. Hilft beim URL-Erhalt, Review und schrittweisen 1:1-Nachbau.
   */
  legacy?: {
    sourceFile?: string | null;
    sourceUrl?: string | null;
    migrationStatus?: ('seeded' | 'reviewed' | 'componentized' | 'live') | null;
    /**
     * Technischer Status fuer Astro: legacy-file und payload-legacy-html sind reine Migrations-/Archivzustaende. native-component und structured-blocks sind release-faehige Ausgabeformen ohne rohes Body-HTML.
     */
    renderSource?: ('legacy-file' | 'payload-legacy-html' | 'native-component' | 'structured-blocks') | null;
    /**
     * Aus der alten Seite extrahierter Head fuer die 1:1-Vorschau und Parity-Routen.
     */
    renderedHeadHtml?: string | null;
    /**
     * Header und Footer sind entfernt. Astro rendert diesen Body aus Payload, solange der Seitentyp noch nicht komplett in strukturierte Komponenten zerlegt ist.
     */
    renderedBodyHtml?: string | null;
    /**
     * Legacy-Skripte und Lightbox-Markup, die nach dem Footer standen.
     */
    afterFooterHtml?: string | null;
    bodyClass?: string | null;
    headerCurrent?: string | null;
    extractedHeadings?: string[] | null;
    extractedImagePaths?: string[] | null;
    /**
     * Reiner Text aus der alten Seite als redaktionelle Kontrollbasis.
     */
    extractedText?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Lokale SEO-Seiten fuer bestehende und neue Suchcluster, inklusive URL-Erhalt und Canonical-Strategie.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "local-seo-pages".
 */
export interface LocalSeoPage {
  id: number;
  title: string;
  /**
   * Wird aus dem Titel erzeugt, kann aber bewusst angepasst werden.
   */
  slug: string;
  priority?: ('high' | 'medium' | 'later') | null;
  city: string;
  service: string;
  intro: string;
  /**
   * Bild aus dem Medienarchiv waehlen. Neue Bilder koennen direkt im Drawer hochgeladen und bearbeitet werden.
   */
  heroImage?: (number | null) | Media;
  localProof?:
    | {
        label: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  localFaq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optionale Inhaltsmodule. Fuer reine Bildwechsel sind die Bildfelder der jeweiligen Seite schneller.
   */
  blocks?:
    | (
        | {
            eyebrow?: string | null;
            headline?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            headline?: string | null;
            layout?: ('editorial-strip' | 'contact-sheet' | 'stage' | 'single-large') | null;
            items?:
              | {
                  /**
                   * Bild fuer diese Position in der Sequenz.
                   */
                  image: number | Media;
                  caption?: string | null;
                  cropIntent?: ('auto' | 'protect-detail' | 'protect-space' | 'dramatic-crop') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageSequence';
          }
        | {
            quote: string;
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteBlock';
          }
        | {
            headline?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
        | {
            headline?: string | null;
            links?:
              | {
                  label: string;
                  /**
                   * Interne Links am besten root-relativ eintragen, z. B. /portfolio. Vollstaendige eigene URLs werden automatisch gekuerzt.
                   */
                  href: string;
                  description?: string | null;
                  seoPurpose?: ('contextual' | 'navigation' | 'conversion' | 'citation' | 'legal' | 'social') | null;
                  rel?: ('follow' | 'nofollow' | 'sponsored' | 'ugc') | null;
                  openInNewTab?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'linkList';
          }
        | {
            headline: string;
            text?: string | null;
            buttonLabel?: string | null;
            emailSubject?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBlock';
          }
      )[]
    | null;
  /**
   * Zum Beispiel: Portraitfotografie Duesseldorf als Hauptseite fuer lokale Varianten.
   */
  canonicalServicePage?: (number | null) | ServicePage;
  /**
   * Wird aus Leistung und Stadt vorgeschlagen, kann aber bewusst angepasst werden.
   */
  targetKeyword?: string | null;
  /**
   * Wird beim Speichern automatisch aus Titel, Intro/Kurztext und Bildfeldern vorbereitet. Nur fuer bewusste Overrides oeffnen.
   */
  seo?: {
    /**
     * Optionaler Override. Wenn leer, wird der Titel automatisch aus dem Seitentitel erzeugt.
     */
    title?: string | null;
    /**
     * Optionaler Override. Wenn leer, wird eine knappe Beschreibung aus Kurztext oder Intro erzeugt.
     */
    description?: string | null;
    /**
     * Optionaler redaktioneller Fokus fuer Snippet, interne Links und spaetere LLM-Vorschlaege.
     */
    focusKeyword?: string | null;
    /**
     * Optional: verwandte Suchbegriffe oder Clusterbegriffe. Nicht stumpf im Text wiederholen.
     */
    secondaryKeywords?: string[] | null;
    /**
     * Hilft beim Schreiben von Title, Description, H1 und internen Links.
     */
    searchIntent?: ('informational' | 'commercial' | 'local' | 'transactional' | 'navigational') | null;
    /**
     * Gewuenschte Anchor-Texte fuer interne Links zu dieser Seite.
     */
    internalLinkAnchors?: string[] | null;
    /**
     * Optionaler Override. Legacy-URLs oder neue Routen werden automatisch vorgeschlagen.
     */
    canonicalUrl?: string | null;
    /**
     * Interne Migrationsnotiz, z. B. portfolio.html oder /automobil-fotografie-duesseldorf.html.
     */
    legacyUrl?: string | null;
    /**
     * Fallback ist das Hero- oder Coverbild. Fuer Social Preview idealerweise 1200x630-nah.
     */
    ogImage?: (number | null) | Media;
    /**
     * Nur für Entwürfe, Übergangsseiten oder bewusst private Inhalte aktivieren.
     */
    noIndex?: boolean | null;
  };
  /**
   * Technische Herkunft aus der alten HTML-Website. Hilft beim URL-Erhalt, Review und schrittweisen 1:1-Nachbau.
   */
  legacy?: {
    sourceFile?: string | null;
    sourceUrl?: string | null;
    migrationStatus?: ('seeded' | 'reviewed' | 'componentized' | 'live') | null;
    /**
     * Technischer Status fuer Astro: legacy-file und payload-legacy-html sind reine Migrations-/Archivzustaende. native-component und structured-blocks sind release-faehige Ausgabeformen ohne rohes Body-HTML.
     */
    renderSource?: ('legacy-file' | 'payload-legacy-html' | 'native-component' | 'structured-blocks') | null;
    /**
     * Aus der alten Seite extrahierter Head fuer die 1:1-Vorschau und Parity-Routen.
     */
    renderedHeadHtml?: string | null;
    /**
     * Header und Footer sind entfernt. Astro rendert diesen Body aus Payload, solange der Seitentyp noch nicht komplett in strukturierte Komponenten zerlegt ist.
     */
    renderedBodyHtml?: string | null;
    /**
     * Legacy-Skripte und Lightbox-Markup, die nach dem Footer standen.
     */
    afterFooterHtml?: string | null;
    bodyClass?: string | null;
    headerCurrent?: string | null;
    extractedHeadings?: string[] | null;
    extractedImagePaths?: string[] | null;
    /**
     * Reiner Text aus der alten Seite als redaktionelle Kontrollbasis.
     */
    extractedText?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'site-pages';
        value: number | SitePage;
      } | null)
    | ({
        relationTo: 'service-pages';
        value: number | ServicePage;
      } | null)
    | ({
        relationTo: 'portfolio-projects';
        value: number | PortfolioProject;
      } | null)
    | ({
        relationTo: 'portfolio-categories';
        value: number | PortfolioCategory;
      } | null)
    | ({
        relationTo: 'journal-posts';
        value: number | JournalPost;
      } | null)
    | ({
        relationTo: 'local-seo-pages';
        value: number | LocalSeoPage;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-pages_select".
 */
export interface SitePagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pageType?: T;
  intro?: T;
  heroImage?: T;
  teaserImage?: T;
  blocks?:
    | T
    | {
        textBlock?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        imageSequence?:
          | T
          | {
              headline?: T;
              layout?: T;
              items?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    cropIntent?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quoteBlock?:
          | T
          | {
              quote?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              headline?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        linkList?:
          | T
          | {
              headline?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    description?: T;
                    seoPurpose?: T;
                    rel?: T;
                    openInNewTab?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBlock?:
          | T
          | {
              headline?: T;
              text?: T;
              buttonLabel?: T;
              emailSubject?: T;
              id?: T;
              blockName?: T;
            };
      };
  contactOverride?:
    | T
    | {
        headline?: T;
        text?: T;
        emailSubject?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        focusKeyword?: T;
        secondaryKeywords?: T;
        searchIntent?: T;
        internalLinkAnchors?: T;
        canonicalUrl?: T;
        legacyUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  legacy?:
    | T
    | {
        sourceFile?: T;
        sourceUrl?: T;
        migrationStatus?: T;
        renderSource?: T;
        renderedHeadHtml?: T;
        renderedBodyHtml?: T;
        afterFooterHtml?: T;
        bodyClass?: T;
        headerCurrent?: T;
        extractedHeadings?: T;
        extractedImagePaths?: T;
        extractedText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-pages_select".
 */
export interface ServicePagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  featured?: T;
  sortOrder?: T;
  serviceType?: T;
  intro?: T;
  heroImage?: T;
  teaserImage?: T;
  audience?:
    | T
    | {
        item?: T;
        id?: T;
      };
  proofPoints?:
    | T
    | {
        label?: T;
        text?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  blocks?:
    | T
    | {
        textBlock?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        imageSequence?:
          | T
          | {
              headline?: T;
              layout?: T;
              items?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    cropIntent?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quoteBlock?:
          | T
          | {
              quote?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              headline?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        linkList?:
          | T
          | {
              headline?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    description?: T;
                    seoPurpose?: T;
                    rel?: T;
                    openInNewTab?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBlock?:
          | T
          | {
              headline?: T;
              text?: T;
              buttonLabel?: T;
              emailSubject?: T;
              id?: T;
              blockName?: T;
            };
      };
  relatedPages?:
    | T
    | {
        label?: T;
        href?: T;
        seoPurpose?: T;
        rel?: T;
        openInNewTab?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        text?: T;
        buttonLabel?: T;
        emailSubject?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        focusKeyword?: T;
        secondaryKeywords?: T;
        searchIntent?: T;
        internalLinkAnchors?: T;
        canonicalUrl?: T;
        legacyUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  legacy?:
    | T
    | {
        sourceFile?: T;
        sourceUrl?: T;
        migrationStatus?: T;
        renderSource?: T;
        renderedHeadHtml?: T;
        renderedBodyHtml?: T;
        afterFooterHtml?: T;
        bodyClass?: T;
        headerCurrent?: T;
        extractedHeadings?: T;
        extractedImagePaths?: T;
        extractedText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-projects_select".
 */
export interface PortfolioProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  featured?: T;
  sortOrder?: T;
  publishedAt?: T;
  category?: T;
  excerpt?: T;
  usageSummary?: T;
  year?: T;
  location?: T;
  client?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        role?: T;
        id?: T;
      };
  relatedServices?: T;
  blocks?:
    | T
    | {
        textBlock?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        imageSequence?:
          | T
          | {
              headline?: T;
              layout?: T;
              items?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    cropIntent?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quoteBlock?:
          | T
          | {
              quote?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              headline?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        linkList?:
          | T
          | {
              headline?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    description?: T;
                    seoPurpose?: T;
                    rel?: T;
                    openInNewTab?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBlock?:
          | T
          | {
              headline?: T;
              text?: T;
              buttonLabel?: T;
              emailSubject?: T;
              id?: T;
              blockName?: T;
            };
      };
  presentationMode?: T;
  cta?:
    | T
    | {
        headline?: T;
        text?: T;
        buttonLabel?: T;
        emailSubject?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        focusKeyword?: T;
        secondaryKeywords?: T;
        searchIntent?: T;
        internalLinkAnchors?: T;
        canonicalUrl?: T;
        legacyUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  legacy?:
    | T
    | {
        sourceFile?: T;
        sourceUrl?: T;
        migrationStatus?: T;
        renderSource?: T;
        renderedHeadHtml?: T;
        renderedBodyHtml?: T;
        afterFooterHtml?: T;
        bodyClass?: T;
        headerCurrent?: T;
        extractedHeadings?: T;
        extractedImagePaths?: T;
        extractedText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-categories_select".
 */
export interface PortfolioCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sortOrder?: T;
  intro?: T;
  coverImage?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        focusKeyword?: T;
        secondaryKeywords?: T;
        searchIntent?: T;
        internalLinkAnchors?: T;
        canonicalUrl?: T;
        legacyUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  legacy?:
    | T
    | {
        sourceFile?: T;
        sourceUrl?: T;
        migrationStatus?: T;
        renderSource?: T;
        renderedHeadHtml?: T;
        renderedBodyHtml?: T;
        afterFooterHtml?: T;
        bodyClass?: T;
        headerCurrent?: T;
        extractedHeadings?: T;
        extractedImagePaths?: T;
        extractedText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-posts_select".
 */
export interface JournalPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  featured?: T;
  category?: T;
  publishedAt?: T;
  excerpt?: T;
  coverImage?: T;
  tags?: T;
  relatedPages?:
    | T
    | {
        label?: T;
        href?: T;
        seoPurpose?: T;
        rel?: T;
        openInNewTab?: T;
        id?: T;
      };
  blocks?:
    | T
    | {
        textBlock?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        imageSequence?:
          | T
          | {
              headline?: T;
              layout?: T;
              items?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    cropIntent?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quoteBlock?:
          | T
          | {
              quote?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              headline?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        linkList?:
          | T
          | {
              headline?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    description?: T;
                    seoPurpose?: T;
                    rel?: T;
                    openInNewTab?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBlock?:
          | T
          | {
              headline?: T;
              text?: T;
              buttonLabel?: T;
              emailSubject?: T;
              id?: T;
              blockName?: T;
            };
      };
  readingTime?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        focusKeyword?: T;
        secondaryKeywords?: T;
        searchIntent?: T;
        internalLinkAnchors?: T;
        canonicalUrl?: T;
        legacyUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  legacy?:
    | T
    | {
        sourceFile?: T;
        sourceUrl?: T;
        migrationStatus?: T;
        renderSource?: T;
        renderedHeadHtml?: T;
        renderedBodyHtml?: T;
        afterFooterHtml?: T;
        bodyClass?: T;
        headerCurrent?: T;
        extractedHeadings?: T;
        extractedImagePaths?: T;
        extractedText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "local-seo-pages_select".
 */
export interface LocalSeoPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  priority?: T;
  city?: T;
  service?: T;
  intro?: T;
  heroImage?: T;
  localProof?:
    | T
    | {
        label?: T;
        text?: T;
        id?: T;
      };
  localFaq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  blocks?:
    | T
    | {
        textBlock?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        imageSequence?:
          | T
          | {
              headline?: T;
              layout?: T;
              items?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    cropIntent?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quoteBlock?:
          | T
          | {
              quote?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              headline?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        linkList?:
          | T
          | {
              headline?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    description?: T;
                    seoPurpose?: T;
                    rel?: T;
                    openInNewTab?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBlock?:
          | T
          | {
              headline?: T;
              text?: T;
              buttonLabel?: T;
              emailSubject?: T;
              id?: T;
              blockName?: T;
            };
      };
  canonicalServicePage?: T;
  targetKeyword?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        focusKeyword?: T;
        secondaryKeywords?: T;
        searchIntent?: T;
        internalLinkAnchors?: T;
        canonicalUrl?: T;
        legacyUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  legacy?:
    | T
    | {
        sourceFile?: T;
        sourceUrl?: T;
        migrationStatus?: T;
        renderSource?: T;
        renderedHeadHtml?: T;
        renderedBodyHtml?: T;
        afterFooterHtml?: T;
        bodyClass?: T;
        headerCurrent?: T;
        extractedHeadings?: T;
        extractedImagePaths?: T;
        extractedText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  title?: T;
  alt?: T;
  caption?: T;
  featured?: T;
  category?: T;
  tags?: T;
  orientation?: T;
  imageType?: T;
  visualTone?: T;
  usagePurpose?: T;
  usageNotes?: T;
  dominantColor?: T;
  blurDataUrl?: T;
  legacySourcePath?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        mobile?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        mobileAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        cardAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        heroAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wideAvif?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Hauptnavigation, Fotografie-Dropdown und Header-CTA passend zur sichtbaren Website-Struktur.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  primary?:
    | {
        label: string;
        /**
         * Interne Links am besten root-relativ eintragen, z. B. /portfolio. Vollstaendige eigene URLs werden automatisch gekuerzt.
         */
        href: string;
        seoPurpose?: ('contextual' | 'navigation' | 'conversion' | 'citation' | 'legal' | 'social') | null;
        rel?: ('follow' | 'nofollow' | 'sponsored' | 'ugc') | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  cta: {
    label?: string | null;
    /**
     * Interne Links am besten root-relativ eintragen, z. B. /portfolio. Vollstaendige eigene URLs werden automatisch gekuerzt.
     */
    href: string;
  };
  photographyLinks?:
    | {
        label: string;
        /**
         * Interne Links am besten root-relativ eintragen, z. B. /portfolio. Vollstaendige eigene URLs werden automatisch gekuerzt.
         */
        href: string;
        seoPurpose?: ('contextual' | 'navigation' | 'conversion' | 'citation' | 'legal' | 'social') | null;
        rel?: ('follow' | 'nofollow' | 'sponsored' | 'ugc') | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  footerLinks?:
    | {
        label: string;
        /**
         * Interne Links am besten root-relativ eintragen, z. B. /portfolio. Vollstaendige eigene URLs werden automatisch gekuerzt.
         */
        href: string;
        seoPurpose?: ('contextual' | 'navigation' | 'conversion' | 'citation' | 'legal' | 'social') | null;
        rel?: ('follow' | 'nofollow' | 'sponsored' | 'ugc') | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        /**
         * Interne Links am besten root-relativ eintragen, z. B. /portfolio. Vollstaendige eigene URLs werden automatisch gekuerzt.
         */
        href: string;
        seoPurpose?: ('contextual' | 'navigation' | 'conversion' | 'citation' | 'legal' | 'social') | null;
        rel?: ('follow' | 'nofollow' | 'sponsored' | 'ugc') | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Website-weite Defaults fuer Marke, Kontakt und SEO-Fallbacks.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteUrl: string;
  locale: string;
  ownerName?: string | null;
  email: string;
  phone?: string | null;
  instagramUrl?: string | null;
  defaultMetaTitle?: string | null;
  defaultMetaDescription?: string | null;
  /**
   * Fallback fuer Open Graph und Social Preview, wenn keine Seite ein eigenes Bild setzt.
   */
  defaultOgImage?: (number | null) | Media;
  footerStatement?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Standard-Anfragebutton und globales Kontaktmodul fuer wiederkehrende Website-Bereiche.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-ctas".
 */
export interface GlobalCta {
  id: number;
  primary: {
    label: string;
    /**
     * Interne Links am besten root-relativ eintragen, z. B. /portfolio. Vollstaendige eigene URLs werden automatisch gekuerzt.
     */
    href: string;
  };
  contactModule?: {
    eyebrow?: string | null;
    headline?: string | null;
    text?: string | null;
    buttonLabel?: string | null;
    emailSubject?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Footer-Struktur, Kontaktzeile, Linkspalten, Social Links und rechtliche Links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  statement?: string | null;
  /**
   * Optionaler Text, der im Frontend innerhalb des Footer-Statements betont werden kann.
   */
  statementHighlight?: string | null;
  email: string;
  phone?: string | null;
  locationLabel?: string | null;
  copyright?: string | null;
  aboutLink: {
    label: string;
    /**
     * Interne Links am besten root-relativ eintragen, z. B. /portfolio. Vollstaendige eigene URLs werden automatisch gekuerzt.
     */
    href: string;
    seoPurpose?: ('contextual' | 'navigation' | 'conversion' | 'citation' | 'legal' | 'social') | null;
    rel?: ('follow' | 'nofollow' | 'sponsored' | 'ugc') | null;
    openInNewTab?: boolean | null;
  };
  /**
   * Canonical Footer-Struktur aus der Legacy-Seite. Jede Spalte bekommt eine Ueberschrift und Links.
   */
  columns?:
    | {
        label: string;
        links?:
          | {
              label: string;
              /**
               * Interne Links am besten root-relativ eintragen, z. B. /portfolio. Vollstaendige eigene URLs werden automatisch gekuerzt.
               */
              href: string;
              seoPurpose?: ('contextual' | 'navigation' | 'conversion' | 'citation' | 'legal' | 'social') | null;
              rel?: ('follow' | 'nofollow' | 'sponsored' | 'ugc') | null;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  primaryLinks?:
    | {
        label: string;
        /**
         * Interne Links am besten root-relativ eintragen, z. B. /portfolio. Vollstaendige eigene URLs werden automatisch gekuerzt.
         */
        href: string;
        seoPurpose?: ('contextual' | 'navigation' | 'conversion' | 'citation' | 'legal' | 'social') | null;
        rel?: ('follow' | 'nofollow' | 'sponsored' | 'ugc') | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  serviceLinks?:
    | {
        label: string;
        /**
         * Interne Links am besten root-relativ eintragen, z. B. /portfolio. Vollstaendige eigene URLs werden automatisch gekuerzt.
         */
        href: string;
        seoPurpose?: ('contextual' | 'navigation' | 'conversion' | 'citation' | 'legal' | 'social') | null;
        rel?: ('follow' | 'nofollow' | 'sponsored' | 'ugc') | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        label: string;
        /**
         * Interne Links am besten root-relativ eintragen, z. B. /portfolio. Vollstaendige eigene URLs werden automatisch gekuerzt.
         */
        href: string;
        seoPurpose?: ('contextual' | 'navigation' | 'conversion' | 'citation' | 'legal' | 'social') | null;
        rel?: ('follow' | 'nofollow' | 'sponsored' | 'ugc') | null;
        openInNewTab?: boolean | null;
        platform?: ('instagram' | 'linkedin' | 'youtube' | 'behance' | 'other') | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        /**
         * Interne Links am besten root-relativ eintragen, z. B. /portfolio. Vollstaendige eigene URLs werden automatisch gekuerzt.
         */
        href: string;
        seoPurpose?: ('contextual' | 'navigation' | 'conversion' | 'citation' | 'legal' | 'social') | null;
        rel?: ('follow' | 'nofollow' | 'sponsored' | 'ugc') | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  primary?:
    | T
    | {
        label?: T;
        href?: T;
        seoPurpose?: T;
        rel?: T;
        openInNewTab?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  photographyLinks?:
    | T
    | {
        label?: T;
        href?: T;
        seoPurpose?: T;
        rel?: T;
        openInNewTab?: T;
        id?: T;
      };
  footerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        seoPurpose?: T;
        rel?: T;
        openInNewTab?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        seoPurpose?: T;
        rel?: T;
        openInNewTab?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteUrl?: T;
  locale?: T;
  ownerName?: T;
  email?: T;
  phone?: T;
  instagramUrl?: T;
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  defaultOgImage?: T;
  footerStatement?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-ctas_select".
 */
export interface GlobalCtasSelect<T extends boolean = true> {
  primary?:
    | T
    | {
        label?: T;
        href?: T;
      };
  contactModule?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        text?: T;
        buttonLabel?: T;
        emailSubject?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  statement?: T;
  statementHighlight?: T;
  email?: T;
  phone?: T;
  locationLabel?: T;
  copyright?: T;
  aboutLink?:
    | T
    | {
        label?: T;
        href?: T;
        seoPurpose?: T;
        rel?: T;
        openInNewTab?: T;
      };
  columns?:
    | T
    | {
        label?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              seoPurpose?: T;
              rel?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  primaryLinks?:
    | T
    | {
        label?: T;
        href?: T;
        seoPurpose?: T;
        rel?: T;
        openInNewTab?: T;
        id?: T;
      };
  serviceLinks?:
    | T
    | {
        label?: T;
        href?: T;
        seoPurpose?: T;
        rel?: T;
        openInNewTab?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        href?: T;
        seoPurpose?: T;
        rel?: T;
        openInNewTab?: T;
        platform?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        seoPurpose?: T;
        rel?: T;
        openInNewTab?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}