/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'portfolio-categories': PortfolioCategory;
    'portfolio-projects': PortfolioProject;
    'service-pages': ServicePage;
    'local-seo-pages': LocalSeoPage;
    'journal-posts': JournalPost;
    'site-pages': SitePage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'portfolio-categories': PortfolioCategoriesSelect<false> | PortfolioCategoriesSelect<true>;
    'portfolio-projects': PortfolioProjectsSelect<false> | PortfolioProjectsSelect<true>;
    'service-pages': ServicePagesSelect<false> | ServicePagesSelect<true>;
    'local-seo-pages': LocalSeoPagesSelect<false> | LocalSeoPagesSelect<true>;
    'journal-posts': JournalPostsSelect<false> | JournalPostsSelect<true>;
    'site-pages': SitePagesSelect<false> | SitePagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    'site-settings': SiteSetting;
    footer: Footer;
    'global-ctas': GlobalCta;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'global-ctas': GlobalCtasSelect<false> | GlobalCtasSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Zentrale Bildbibliothek mit SEO-Alttexten, Bildstimmung, Verwendungszweck und responsiven Derivaten.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Redaktioneller Name, nicht nur Dateiname.
   */
  title: string;
  /**
   * Beschreibt das Bild knapp für SEO und Barrierefreiheit.
   */
  alt: string;
  caption?: string | null;
  category?: ('portrait' | 'automotive' | 'oldtimer' | 'motorrad' | 'landschaft' | 'service' | 'atmosphere') | null;
  /**
   * Freie Schlagworte, z. B. Düsseldorf, Nacht, Showroom, Detail, Kampagne.
   */
  tags?: string[] | null;
  orientation?: ('portrait' | 'landscape' | 'square' | 'panorama') | null;
  /**
   * Hilft später beim Filtern und Wiederfinden geeigneter Bilder.
   */
  imageType?:
    | (
        | 'portrait'
        | 'automotive'
        | 'landscape'
        | 'motorcycle'
        | 'detail'
        | 'editorial'
        | 'atmosphere'
        | 'behind-the-scenes'
      )[]
    | null;
  visualTone?:
    | ('dark-cinematic' | 'light-editorial' | 'warm-atmospheric' | 'cool-technical' | 'detail-texture')[]
    | null;
  usagePurpose?: ('hero' | 'teaser' | 'gallery' | 'social' | 'local-seo' | 'print' | 'internal-only')[] | null;
  /**
   * Für besonders starke Motive, die als Hero oder Portfolio-Teaser in Frage kommen.
   */
  featured?: boolean | null;
  /**
   * Zum Beispiel: gutes Hero-Motiv, nicht stark beschneiden, für Portfolio-Teaser geeignet.
   */
  usageNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    mobile?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-categories".
 */
export interface PortfolioCategory {
  id: number;
  title: string;
  /**
   * Wird aus dem Titel erzeugt, kann aber bewusst angepasst werden.
   */
  slug: string;
  sortOrder?: number | null;
  intro?: string | null;
  coverImage?: (number | null) | Media;
  /**
   * Suchsnippet und Social Preview. Leer lassen, wenn die Seite automatisch aus Titel/Intro ableiten soll.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Nur für Entwürfe, Übergangsseiten oder bewusst private Inhalte aktivieren.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-projects".
 */
export interface PortfolioProject {
  id: number;
  title: string;
  /**
   * Wird aus dem Titel erzeugt, kann aber bewusst angepasst werden.
   */
  slug: string;
  featured?: boolean | null;
  /**
   * Kleinere Werte erscheinen weiter oben.
   */
  sortOrder?: number | null;
  publishedAt?: string | null;
  category: number | PortfolioCategory;
  /**
   * Steuert die visuelle Logik im Astro-Template.
   */
  presentationMode?: ('floating-archive' | 'narrative-stage' | 'experimental-lens' | 'editorial') | null;
  excerpt: string;
  /**
   * Kurz notieren, wofür die Serie gedacht ist: Verkauf, Kampagne, Print, Website, freie Arbeit.
   */
  usageSummary?: string | null;
  year?: string | null;
  location?: string | null;
  client?: string | null;
  coverImage: number | Media;
  relatedServices?: (number | ServicePage)[] | null;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        role?: ('hero' | 'sequence' | 'detail' | 'closing') | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    headline?: string | null;
    text?: string | null;
    buttonLabel?: string | null;
    emailSubject?: string | null;
  };
  blocks?:
    | (
        | {
            eyebrow?: string | null;
            headline?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            headline?: string | null;
            layout?: ('editorial-strip' | 'contact-sheet' | 'stage' | 'single-large') | null;
            items?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  cropIntent?: ('auto' | 'protect-detail' | 'protect-space' | 'dramatic-crop') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageSequence';
          }
        | {
            quote: string;
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteBlock';
          }
        | {
            headline?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
        | {
            headline?: string | null;
            links?:
              | {
                  label: string;
                  href: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'linkList';
          }
        | {
            headline: string;
            text?: string | null;
            buttonLabel?: string | null;
            emailSubject?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBlock';
          }
      )[]
    | null;
  /**
   * Suchsnippet und Social Preview. Leer lassen, wenn die Seite automatisch aus Titel/Intro ableiten soll.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Nur für Entwürfe, Übergangsseiten oder bewusst private Inhalte aktivieren.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-pages".
 */
export interface ServicePage {
  id: number;
  title: string;
  /**
   * Wird aus dem Titel erzeugt, kann aber bewusst angepasst werden.
   */
  slug: string;
  featured?: boolean | null;
  sortOrder?: number | null;
  serviceType:
    | 'automotive'
    | 'sportwagen'
    | 'oldtimer'
    | 'motorrad'
    | 'portrait'
    | 'landschaft'
    | 'fotolabor'
    | 'grossformatdruck'
    | 'werbetechnik'
    | 'webdesign-seo'
    | 'videografie'
    | 'other';
  heroImage: number | Media;
  teaserImage?: (number | null) | Media;
  intro: string;
  audience?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  proofPoints?:
    | {
        label: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  relatedPages?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    headline?: string | null;
    text?: string | null;
    buttonLabel?: string | null;
    emailSubject?: string | null;
  };
  blocks?:
    | (
        | {
            eyebrow?: string | null;
            headline?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            headline?: string | null;
            layout?: ('editorial-strip' | 'contact-sheet' | 'stage' | 'single-large') | null;
            items?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  cropIntent?: ('auto' | 'protect-detail' | 'protect-space' | 'dramatic-crop') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageSequence';
          }
        | {
            quote: string;
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteBlock';
          }
        | {
            headline?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
        | {
            headline?: string | null;
            links?:
              | {
                  label: string;
                  href: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'linkList';
          }
        | {
            headline: string;
            text?: string | null;
            buttonLabel?: string | null;
            emailSubject?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBlock';
          }
      )[]
    | null;
  /**
   * Suchsnippet und Social Preview. Leer lassen, wenn die Seite automatisch aus Titel/Intro ableiten soll.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Nur für Entwürfe, Übergangsseiten oder bewusst private Inhalte aktivieren.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "local-seo-pages".
 */
export interface LocalSeoPage {
  id: number;
  title: string;
  /**
   * Wird aus dem Titel erzeugt, kann aber bewusst angepasst werden.
   */
  slug: string;
  priority?: ('high' | 'medium' | 'later') | null;
  city: string;
  service: string;
  /**
   * Zum Beispiel: Portraitfotografie Düsseldorf als Hauptseite für lokale Varianten.
   */
  canonicalServicePage?: (number | null) | ServicePage;
  heroImage?: (number | null) | Media;
  /**
   * Nur zur redaktionellen Orientierung, nicht automatisch plump ausgeben.
   */
  targetKeyword?: string | null;
  intro: string;
  localProof?:
    | {
        label: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  localFaq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  blocks?:
    | (
        | {
            eyebrow?: string | null;
            headline?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            headline?: string | null;
            layout?: ('editorial-strip' | 'contact-sheet' | 'stage' | 'single-large') | null;
            items?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  cropIntent?: ('auto' | 'protect-detail' | 'protect-space' | 'dramatic-crop') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageSequence';
          }
        | {
            quote: string;
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteBlock';
          }
        | {
            headline?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
        | {
            headline?: string | null;
            links?:
              | {
                  label: string;
                  href: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'linkList';
          }
        | {
            headline: string;
            text?: string | null;
            buttonLabel?: string | null;
            emailSubject?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBlock';
          }
      )[]
    | null;
  /**
   * Suchsnippet und Social Preview. Leer lassen, wenn die Seite automatisch aus Titel/Intro ableiten soll.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Nur für Entwürfe, Übergangsseiten oder bewusst private Inhalte aktivieren.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-posts".
 */
export interface JournalPost {
  id: number;
  title: string;
  /**
   * Wird aus dem Titel erzeugt, kann aber bewusst angepasst werden.
   */
  slug: string;
  featured?: boolean | null;
  category: 'behind-the-scenes' | 'automotive' | 'portrait' | 'landscape-print' | 'process';
  publishedAt: string;
  coverImage: number | Media;
  excerpt: string;
  readingTime?: number | null;
  tags?: string[] | null;
  relatedPages?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  blocks?:
    | (
        | {
            eyebrow?: string | null;
            headline?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            headline?: string | null;
            layout?: ('editorial-strip' | 'contact-sheet' | 'stage' | 'single-large') | null;
            items?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  cropIntent?: ('auto' | 'protect-detail' | 'protect-space' | 'dramatic-crop') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageSequence';
          }
        | {
            quote: string;
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteBlock';
          }
        | {
            headline?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
        | {
            headline?: string | null;
            links?:
              | {
                  label: string;
                  href: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'linkList';
          }
        | {
            headline: string;
            text?: string | null;
            buttonLabel?: string | null;
            emailSubject?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBlock';
          }
      )[]
    | null;
  /**
   * Suchsnippet und Social Preview. Leer lassen, wenn die Seite automatisch aus Titel/Intro ableiten soll.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Nur für Entwürfe, Übergangsseiten oder bewusst private Inhalte aktivieren.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-pages".
 */
export interface SitePage {
  id: number;
  title: string;
  /**
   * Wird aus dem Titel erzeugt, kann aber bewusst angepasst werden.
   */
  slug: string;
  pageType: 'home' | 'about' | 'contact' | 'portfolio-index' | 'services-index' | 'journal-index' | 'legal';
  heroImage?: (number | null) | Media;
  teaserImage?: (number | null) | Media;
  intro?: string | null;
  contactOverride?: {
    headline?: string | null;
    text?: string | null;
    emailSubject?: string | null;
  };
  blocks?:
    | (
        | {
            eyebrow?: string | null;
            headline?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            headline?: string | null;
            layout?: ('editorial-strip' | 'contact-sheet' | 'stage' | 'single-large') | null;
            items?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  cropIntent?: ('auto' | 'protect-detail' | 'protect-space' | 'dramatic-crop') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageSequence';
          }
        | {
            quote: string;
            attribution?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteBlock';
          }
        | {
            headline?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
        | {
            headline?: string | null;
            links?:
              | {
                  label: string;
                  href: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'linkList';
          }
        | {
            headline: string;
            text?: string | null;
            buttonLabel?: string | null;
            emailSubject?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBlock';
          }
      )[]
    | null;
  /**
   * Suchsnippet und Social Preview. Leer lassen, wenn die Seite automatisch aus Titel/Intro ableiten soll.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Nur für Entwürfe, Übergangsseiten oder bewusst private Inhalte aktivieren.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'portfolio-categories';
        value: number | PortfolioCategory;
      } | null)
    | ({
        relationTo: 'portfolio-projects';
        value: number | PortfolioProject;
      } | null)
    | ({
        relationTo: 'service-pages';
        value: number | ServicePage;
      } | null)
    | ({
        relationTo: 'local-seo-pages';
        value: number | LocalSeoPage;
      } | null)
    | ({
        relationTo: 'journal-posts';
        value: number | JournalPost;
      } | null)
    | ({
        relationTo: 'site-pages';
        value: number | SitePage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  title?: T;
  alt?: T;
  caption?: T;
  category?: T;
  tags?: T;
  orientation?: T;
  imageType?: T;
  visualTone?: T;
  usagePurpose?: T;
  featured?: T;
  usageNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        mobile?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-categories_select".
 */
export interface PortfolioCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sortOrder?: T;
  intro?: T;
  coverImage?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-projects_select".
 */
export interface PortfolioProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  featured?: T;
  sortOrder?: T;
  publishedAt?: T;
  category?: T;
  presentationMode?: T;
  excerpt?: T;
  usageSummary?: T;
  year?: T;
  location?: T;
  client?: T;
  coverImage?: T;
  relatedServices?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        role?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        text?: T;
        buttonLabel?: T;
        emailSubject?: T;
      };
  blocks?:
    | T
    | {
        textBlock?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        imageSequence?:
          | T
          | {
              headline?: T;
              layout?: T;
              items?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    cropIntent?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quoteBlock?:
          | T
          | {
              quote?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              headline?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        linkList?:
          | T
          | {
              headline?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBlock?:
          | T
          | {
              headline?: T;
              text?: T;
              buttonLabel?: T;
              emailSubject?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-pages_select".
 */
export interface ServicePagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  featured?: T;
  sortOrder?: T;
  serviceType?: T;
  heroImage?: T;
  teaserImage?: T;
  intro?: T;
  audience?:
    | T
    | {
        item?: T;
        id?: T;
      };
  proofPoints?:
    | T
    | {
        label?: T;
        text?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedPages?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        text?: T;
        buttonLabel?: T;
        emailSubject?: T;
      };
  blocks?:
    | T
    | {
        textBlock?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        imageSequence?:
          | T
          | {
              headline?: T;
              layout?: T;
              items?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    cropIntent?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quoteBlock?:
          | T
          | {
              quote?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              headline?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        linkList?:
          | T
          | {
              headline?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBlock?:
          | T
          | {
              headline?: T;
              text?: T;
              buttonLabel?: T;
              emailSubject?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "local-seo-pages_select".
 */
export interface LocalSeoPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  priority?: T;
  city?: T;
  service?: T;
  canonicalServicePage?: T;
  heroImage?: T;
  targetKeyword?: T;
  intro?: T;
  localProof?:
    | T
    | {
        label?: T;
        text?: T;
        id?: T;
      };
  localFaq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  blocks?:
    | T
    | {
        textBlock?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        imageSequence?:
          | T
          | {
              headline?: T;
              layout?: T;
              items?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    cropIntent?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quoteBlock?:
          | T
          | {
              quote?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              headline?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        linkList?:
          | T
          | {
              headline?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBlock?:
          | T
          | {
              headline?: T;
              text?: T;
              buttonLabel?: T;
              emailSubject?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-posts_select".
 */
export interface JournalPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  featured?: T;
  category?: T;
  publishedAt?: T;
  coverImage?: T;
  excerpt?: T;
  readingTime?: T;
  tags?: T;
  relatedPages?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  blocks?:
    | T
    | {
        textBlock?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        imageSequence?:
          | T
          | {
              headline?: T;
              layout?: T;
              items?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    cropIntent?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quoteBlock?:
          | T
          | {
              quote?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              headline?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        linkList?:
          | T
          | {
              headline?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBlock?:
          | T
          | {
              headline?: T;
              text?: T;
              buttonLabel?: T;
              emailSubject?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-pages_select".
 */
export interface SitePagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pageType?: T;
  heroImage?: T;
  teaserImage?: T;
  intro?: T;
  contactOverride?:
    | T
    | {
        headline?: T;
        text?: T;
        emailSubject?: T;
      };
  blocks?:
    | T
    | {
        textBlock?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        imageSequence?:
          | T
          | {
              headline?: T;
              layout?: T;
              items?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    cropIntent?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quoteBlock?:
          | T
          | {
              quote?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              headline?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        linkList?:
          | T
          | {
              headline?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBlock?:
          | T
          | {
              headline?: T;
              text?: T;
              buttonLabel?: T;
              emailSubject?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  primary?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  photographyLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteUrl: string;
  locale: string;
  defaultMetaTitle?: string | null;
  defaultMetaDescription?: string | null;
  ownerName?: string | null;
  email: string;
  phone?: string | null;
  instagramUrl?: string | null;
  defaultOgImage?: (number | null) | Media;
  footerStatement?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  statement?: string | null;
  email: string;
  phone?: string | null;
  locationLabel?: string | null;
  primaryLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  serviceLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        label: string;
        href: string;
        platform?: ('instagram' | 'linkedin' | 'youtube' | 'behance' | 'other') | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-ctas".
 */
export interface GlobalCta {
  id: number;
  primary: {
    label: string;
    href: string;
  };
  contactModule?: {
    eyebrow?: string | null;
    headline?: string | null;
    text?: string | null;
    buttonLabel?: string | null;
    emailSubject?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  primary?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  photographyLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteUrl?: T;
  locale?: T;
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  ownerName?: T;
  email?: T;
  phone?: T;
  instagramUrl?: T;
  defaultOgImage?: T;
  footerStatement?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  statement?: T;
  email?: T;
  phone?: T;
  locationLabel?: T;
  primaryLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  serviceLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        href?: T;
        platform?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-ctas_select".
 */
export interface GlobalCtasSelect<T extends boolean = true> {
  primary?:
    | T
    | {
        label?: T;
        href?: T;
      };
  contactModule?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        text?: T;
        buttonLabel?: T;
        emailSubject?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}